### PR TITLE
Added pug template support

### PR DESCRIPTION
**Pull request by ghost**
So `lang="pug"` can be specified in templates.

### CODE REVIEW

**Comment by differui** [comment]
Hi @g3ngar thanks for your pr. Here is the new package: [ko-component-compiler@0.5.0](https://www.npmjs.com/package/ko-component-compiler)
p.s. knockout is an old day framework, recommend you try other trendy ones.

**Comment by ghost** [comment]
You're welcome. I know ko is a little old, but I like it a lot; it's very easy to use and combine with other frameworks and existing code.

Can you please update rollup-plugin-ko so it uses this new version?

**Comment by differui** [comment]
it's done!
[rollup-plugin-ko@0.4.0](https://www.npmjs.com/package/rollup-plugin-ko)

**Comment by ghost** [comment]
Great! Thanks!

**Pull request merged**
